version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    #image: gcr.io/strategic-reef-435523-j1/pythonproject-backend:latest
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"  # Map port 5000 on host to port 5000 in the container
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    #image: gcr.io/strategic-reef-435523-j1/pythonproject-frontend:latest
    ports:
      - "8080:80"  # Map port 8080 on host to port 80 in the container
    networks:
      - my_network

networks:
  my_network:
