apiVersion: v1
kind: Secret
metadata:
  name: myapp-secrets
type: Opaque
data:
  db_username: bXl1c2Vy  # Base64 encoded value for username
  db_password: U2hyYXZ5YTEyMw==  # Base64 encoded value for password
  gcs_bucket_name: bXktZmxhc2staW1hZ2UtdXBsb2FkLWJ1Y2tldA==  # Base64 encoded value for GCP bucket
